### ISSUE TITLE
Reduce user authentication permissions

### ISSUE THREAD

**Issue by Baa14453** [TitanEmbeds/Titan#155]
When a user authenticates with Titan the bot will request access to:
- Username
- Discord Guilds
- Join Server

I'm concerned these permissions will deter some users from authorising, it should be possible to authenticate users for chat with only Username. Rather than join automatically users can be invited, and list of discord guilds shouldn't be required. If the bot has already joined the guild it then comparing the user's username against the guild's membership list to check if they are a member possibly

**Comment by omnicons** [comment]
The behavior you are mentioning is intentional on our part and not something we would be willing to reconfigure for our main instance. If these permissions do not work for your users then using guest authentication would probably serve you better that way they don't need these permissions. Or if you absolutely must, you can fork the repository and create defaults that suit your purposes as this main repo is mainly for our public instance that we host and maintain.

The reason the public instance needs to grab the user's list of guilds is that depending on which shard the user gets the results could return false negatives and it is better to just check to see if they are in the appropriate guild. There have been slight discussion of possible rewrites and reworks of Titan that could address something like this but this is technically not an issue for this version as it is working as intended. 

It this will be added to a features list for the future but as far as this current version of Titan is concerned this is a feature request and not a bug.
